/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-08 22:35:01
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  ll sum = 0;
  int mx = 0, cmx = 0;
  vector<int> a(n); 
  for (int &x: a) {
    cin >> x, sum += x;
    if (x >= mx) {
      cmx = mx;
      mx = x;
    } else {
      chkmax(cmx, x);
    }
  }
  int cnt = 0;
  // cout << mx << " " << cmx << "\n";
  for (int i = 0; i < n; i ++ ) {
    if (a[i] == mx) {
      // cmx 
      // if ((sum - cmx - mx) )
      ll p = sum - cmx - mx; // other
      p = cmx - p; // cmx last
      if (p < a[i]) {
        ++ cnt;
      }
    } else {
      ll p = sum - a[i] - mx; // other
      p = mx - p;
      if (p < a[i]) {
        ++ cnt;
      }
    }
  }

  cout << cnt  << "\n";
 
}

void solve2() {
  int n; cin >> n;
  vector<int> a(n); for (int &x: a) cin >> x;
  int id = 0;
  for (int i = 1; i < n; i ++ ) if (a[i] > a[id]) {
    id = i;
  }
  cout << id + 1 << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve2();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
