/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-23 17:25:03
**/

#include <bits/stdc++.h>
// using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n, q; 
  std::cin >> n >> q;

  std::vector<int> a(n);
  for (int i = 0; i < n; i ++ ) {
    std::cin >> a[i];
  }

  if (n == 1) {
    while (q -- ) {
      std::cout << "1\n";
    }
    return ;
  }

  // a[2] = 2;

  ll ans = 1, last = 1;

  // std::vector<ll> last(n);
  // last[0] = 1;

  for (int i = 1; i < n; i ++ ) {
    // last[i] = last[i - 1];
    if (a[i] != a[i - 1]) {
      // last[i] ++;
      last ++;
    } 
    // ans += last[i];
    ans += last;
  }

  ll all = ans;

  for (int i = 1; i < n; i ++ ) {
    if (a[i] == a[i - 1]) {
      ans -= 1;
    } else {
      ans -= (n - i + 1);
    }
    all += ans;
  }


  while (q -- ) {
    int idx, x; 
    std::cin >> idx >> x; idx -- ;
    if (a[idx] == x) {
      std::cout << all << "\n";
      continue;
    }

    

    if (idx == n - 1) {
      if (a[idx] == a[idx - 1]) {
        all += n - 1;
      } else if(a[idx - 1] == x) {
        all -= n - 1;
      }
    } else if(idx == 0) {
      if (a[idx] == a[idx + 1]) {
        all += n - 1;
      } else if(a[idx + 1] == x) {
        all -= n - 1;
      }
    } else {
      if (a[idx] == a[idx - 1]) {
        all += 1ll * idx * (n - idx);
      } else if(a[idx - 1] == x) {
        all -= 1ll * idx * (n - idx);
      }

      if (a[idx] == a[idx + 1]) {
        all += 1ll * (idx + 1) * (n - idx - 1);
      } else if(a[idx + 1] == x) {
        all -= 1ll * (idx + 1) * (n - idx - 1);
      }

    }

    a[idx] = x;

    std::cout << all << "\n";

  }

}

int main() {
  std::cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; 
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
