/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-11-20 17:57:35
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  string s = "Yes";
  
  string t; cin >> t;
  // for (char &c: t) c = toupper(c);
  bool flag = true;
  for (int i = 0; i < t.size() && flag; i ++ ) if (t[i] != s[i % 3]) {
    flag = false;
  }
  if (flag) return cout << "YES\n", void();
  s = "esY";
  flag = true;
  for (int i = 0; i < t.size() && flag; i ++ ) if (t[i] != s[i % 3]) {
    flag = false;
  }
  if (flag) return cout << "YES\n", void();
  s = "sYe";
  flag = true;
  for (int i = 0; i < t.size() && flag; i ++ ) if (t[i] != s[i % 3]) {
    flag = false;
  }
  if (flag) return cout << "YES\n", void();

  cout << "NO\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
