/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-30 13:47:50
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 2E5 + 10;

int n, q;

struct node {
  ll h, a, b, c; 
  bool operator < (const node &T) const {
    if (c >= 0 && T.c >= 0) return h < T.h;
    else if (c < 0 && T.c < 0) return c + h > T.c + T.h; 
    else return c > T.c;
  }
} a[N];

ll gen() {
  ll ans = a[1].h;
  ll now = a[1].h;
  for (int i = 1; i <= n; i ++ ) {
    if (now < a[i].h) {
      ans += a[i].h - now;
      now = a[i].h;
    }
    now += a[i].b - a[i].a;
  }
  return ans;
}

void solve() {
  cin >> n;
  for (int i = 1; i <= n; i ++ ) cin >> a[i].h;
  for(int i = 1; i <= n; i ++ ) {
    cin >> a[i].a >> a[i].b;
    a[i].c = a[i].b - a[i].a;
  }
  sort(a + 1, a + 1 + n);
  // for(int i = 1; i <= n; i ++ ) {
  //   cout << a[i].h << " " << a[i].a << " " << a[i].b << "\n";
  // }
  cout << gen() << "\n";
  cin >> q;
  while (q -- ) {
    node t; cin >> t.h >> t.a >> t.b; t.c = t.b - t.a;
    int pos = lower_bound(a + 1, a + 1 + n, t) - a;
    for (int i = n; i >= pos; i -- ) {
      a[i + 1] = a[i];
    }
    a[pos] = t;
    ++ n;
    cout << gen() << "\n";
  }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; // cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
