/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-08 22:35:01
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define rep(i,a,b) for (int i(a); i <= b; ++ i)
#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 2E5 + 10;

int a[N], b[N];
// int A[N], B[N];
int gen(int x, int cnt) {
  if (!cnt) return x;
  int len = to_string(x).size();
  if (cnt == 1) return len;
  len = to_string(len).size();
  return len;
}

int get(int x, int y) {
  int mi = INT_MAX;
  for (int i = 0; i < 3; i ++ ) {
    for (int j = 0; j < 3; j ++ ) {
      int p = x, q = y;
      if (gen(p, i) == gen(q, j)) {
        chkmin(mi, i + j);
      }
    }
  }
  return mi;
  // x -> len(x) [1, 9]
  // y -> len(y) [1, 9]

}

// vector<int> fa[10], fb[10];
int fa[10], fb[10];

void solve() {
  int n, m = 0; cin >> n;
  map<int, int> mp;
  for (int i = 0; i < 10; i ++ ) {
    // fa[i].clear(); fb[i].clear();
    fa[i] = fb[i] = 0;
  }
  int ans = 0;
  rep(i, 1, n) cin >> a[i], mp[a[i]] ++;
  rep(i, 1, n) {
    cin >> b[i];
    if (mp[b[i]] > 0) {
      mp[b[i]] --;
    } else {
      if (b[i] < 10) {
        fb[b[i]] ++;
      } else {
        ++ ans;
        fb[(int)to_string(b[i]).size()] ++;
      }
    }
  }

  for (auto [k, v]: mp) if (v > 0) {
    
    auto K = k;
    if (K < 10) {
      fa[K] += v;
    } else {
      // ++ ans;
      ans += v;
      fa[(int)to_string(K).size()] += v;
    }
  }

  for (int i = 0; i < 10; i ++ ) {
    int mi = min(fa[i], fb[i]);
    fa[i] -= mi; fb[i] -= mi;
  }
  // cout << ans << "\n";
  for (int i = 2; i < 10; i ++ ) {
    ans += fa[i] + fb[i];
  }
  cout << ans << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */