/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-10-18 13:54:40
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

map<ll, int> f(ll x) {
  map<ll, int> mp;
  for (ll i = 2; i * i <= x; i ++ ) if (x % i == 0) {
    while (x % i == 0) {
      mp[i] ++;
      x /= i;
    }
  }
  if (x != 1) mp[x] ++;
  return mp;
}

void solve() {
  ll a, b, c, d;
  cin >> a >> b >> c >> d;
  map<ll, int> mp;
  auto mpa = f(a);
  for (auto &[k, v] : mpa) {
    mp[k] += v;
  }
  auto mpb = f(b);
  for (auto &[k, v] : mpb) {
    mp[k] += v;
  }
  
  vector<pair<ll, int> > A;

  for (auto &[k, v]: mp) {
    A.emplace_back(k, v);
  }

  int n = A.size();
  ll sum = a * b;
  ll ans = 0;
  bool flag = false;
  function<void(int, ll)> dfs = [&] (int i, ll p) {
    if (flag) return ;
    if (i == n) {
      ll q = sum / p;
      // p *= 2, q *= 2;
      if (p <= a) p = (a + 1 + p - 1) / p * p;
      if (q <= b) q = (b + 1 + q - 1) / q * q;

      // debug(a, p, c, b, q, d);
      if (p >= a && p <= c && q >= b && q <= d) {
        cout << p << " " << q << "\n";
        flag = true;
      }
      return ;
    }
    for (int j = 0; j <= A[i].second; j ++ ) {
      dfs(i + 1, p);
      p *= A[i].first;
    }
  };

  dfs (0, 1);

  if (!flag) {
    cout << "-1 -1\n";
  }



}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
