/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-12-01 15:20:01
**/

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

#define pb push_back
#define eb emplace_back
#define maxe max_element
#define mine min_element
#define ay2 array<int, 2>
#define PII pair<int, int>
#define SZ(a) ((int)a.size()) 
#define all(v) v.begin(), v.end()
#define Rep(i, a, b) for (int i(a); i < b; ++ i ) 
#define rep(i, a, b) for (int i(a); i <= b; ++ i ) 
#define dec(i, a, b) for (int i(b); i >= a; -- i ) 

#ifdef LOCAL
  #include <debugger>
#else
  #define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

// mt19937 rnd(random_device{}()); 
mt19937_64 mrand(chrono::steady_clock::now().time_since_epoch().count());
int rnd(int x) { return mrand() % x;}

constexpr int INF = 0x3f3f3f3f;
constexpr ll INFF = 0x3f3f3f3f3f3f3f3f;
// constexpr int N = 2E5 + 10;

void solve() {
  int n; cin >> n;
  vector<double> a(n);
  for (double &x: a) cin >> x;
  if (n <= 2) return cout << "0\n", void();
  int ans = n - 2;
  for (int i = 0; i < n; i ++ ) {
    for (int j = i + 1; j < n; j ++ ) {
      double d = (a[j] - a[i]) / (j - i);
      // debug(i, j, d);
      double first = a[i] - d * i;
      int ret = 0;
      for (int k = 0; k < n; k ++ )  {
        if (fabs(a[k] - first) >= 1E-8) ret ++;
        first += d;
        // debug(k, a[k], first);
      }
      chkmin(ans, ret);
    }
  }
  // for (int d = -200; d <= 200; d ++ ) { //1E4

  //   for (int i = 0; i < n; i ++ ) {
  //     int ret = 0; int inc = 0;
  //     for (int j = i + 1; j < n; j ++ ) {
  //       inc += d;
  //       if (a[j] != a[i] + inc) ++ ret;
  //     }
  //     inc = 0;
  //     for (int j = i - 1; j >= 0; j -- ) {
  //       inc -= d;
  //       if (a[j] != a[i] + inc) ++ ret;
  //     }
  //     chkmin(ans, ret);
  //   }
  // }
  cout << ans << "\n";
  //

}
int main() {
  cin.tie(nullptr)->sync_with_stdio(false);

  int T; cin >> T;
  while (T --) {
    solve();
  }
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
