/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-23 17:25:03
**/

#include <bits/stdc++.h>
// using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }


void solve() {
  int n, q; 
  std::cin >> n >> q;
  std::vector<int> f(n, (1 << 30) - 1);
  std::vector<std::vector<std::array<int, 2> > > adj(n);

  while (q -- ) {
    int a, b, c; 
    std::cin >> a >> b >> c;
    -- a, -- b;
    f[a] &= c;
    f[b] &= c;
    adj[a].push_back({b, c});
    adj[b].push_back({a, c});
  }

  for (int i = 0; i < n; i ++ ) {
    int t = 0;
    for (auto &[j, x]: adj[i]) {
      t |= x & ~f[j];
      if (j == i) {
        t = x;
        break;
      }
    }
    f[i] = t;
    std::cout << f[i] << " \n"[i == n - 1];
  }
}

constexpr int P = (1 << 30) - 1;

void solve2() {
  int n, q; 
  std::cin >> n >> q;
  
  std::vector<int> a(n);
  std::vector<std::vector<std::array<int, 2> > > son(n);
  std::vector<int> ban(n);


  while (q -- ) {
    int x, y, val; 
    std::cin >> x >> y >> val;
    -- x, -- y;
    ban[x] |= ~val & P; //表示 x 不能选的
    ban[y] |= ~val & P;
    son[x].push_back({y, val});
    son[y].push_back({x, val});
  }

  for (int i = 0; i < n; i ++ ) {
    sort(son[i].begin(), son[i].end());
    for (auto& [j, val]: son[i]) {
      if (j < i) {
        //如果是 < 说明已经确定了, 那么a[j]没选的，a[i] 一定得选
        a[i] |= ~a[j] & val;
      } else if(i == j) {
        a[i] = val;
        break;
      } else {
        //a[i] 还没选，那么能不选尽量不选, 但是 j 不能选的，i一定要选
        a[i] |= val & ban[j]; 
      }
    }
    std::cout << a[i] << " \n"[i == n - 1];
  }

  


}

int main() {
  std::cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; //cin >> T;
  while (T --) solve2();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
