/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-29 22:35:13
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 110;

int a[N], d[N];

void solve() {
  int n; cin >> n;
  for (int i = 1; i <= n; i ++ ) cin >> d[i];
  a[1] = d[1];
  for (int i = 2; i <= n; i ++ ) {
    if (d[i] == 0) {
      a[i] = a[i - 1]; continue;
    }
    if (a[i - 1] > d[i]) {
      cout << "-1\n";
      return ;
    }
    a[i] = a[i - 1] + d[i];
  }
  for (int i = 1; i <= n; i ++ ) cout << a[i]  << " \n"[i == n];

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
