/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-12 22:36:26
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  string s; cin >> s;
  int n = s.size();
  s = " " + s;
  vector<int> S(n + 1);
  for (int i = 1; i <= n; i ++ ) {
    S[i] = S[i - 1] + (s[i] - '0');
  }

  int w, q; cin >> w >> q;
  
  vector<vector<int> > f(9);
  
  for (int i = 0; i + w <= n; i ++ ) {
    f[(S[i + w] - S[i]) % 9].push_back(i + 1);
  }

  auto Nanfeng = [&] () {
    int l, r, k; cin >> l >> r >> k;
    pair<int, int> ans = {INT_MAX, INT_MAX};
    int v = (S[r] - S[l - 1]) % 9;
    for (int i = 0; i < 9; i ++ ) {
      for (int j = 0; j < 9; j ++ ) {
        if ((i * v + j) % 9 == k) {
          if (i == j) {
            if ((int)f[i].size() >= 2) {
              chkmin(ans, make_pair(f[i][0], f[i][1]));
            }
          } else {
            if (!f[i].empty() && !f[j].empty()) {
              chkmin(ans, make_pair(f[i][0], f[j][0]));
            }
          }
        }
      }
    }
    if (ans == make_pair(INT_MAX, INT_MAX)) {
      cout << "-1 -1\n";
    } else {
      cout << ans.first << " " << ans.second << "\n";
    }
    
  };

  while (q -- ) {
    Nanfeng();
  }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
