/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-12 22:36:26
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  string s; cin >> s;
  int n = s.size();
  vector<int> vis(26);
  vector<vector<int> > son(26);
  for (int i = 0; i < n; i ++ ) {
    int now = s[i] - 'a';
    son[now].push_back(i);
    vis[now] ++;
  }
  // for (char c: s) vis[c - 'a'] ++;
  
  int left = s[0] - 'a', right = s.back() - 'a';
  vector<int> ans;
  if (left <= right) {
    for (int i = left; i <= right; i ++ ) {
      for (auto t: son[i]) {
        ans.push_back(t);
      }
    }
  } else {
    for (int i = left; i >= right; i -- ) {
      for (auto t: son[i]) {
        ans.push_back(t);
      }
    }
  }
  cout << abs(right - left) << " " << ans.size() << "\n";
  for (int x: ans) cout << x + 1 << " ";
  cout << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
