/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-06 22:35:02
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  vector<int> a(n);
  for (int &x: a) cin >> x;
  if (n == 1) {
    cout << "0\n";
    return ;
  }
  // case1: 
  int ans = INT_MIN;
  for (int i = 0; i < n; i ++ ) {
    int l = i, r = (n - 1 + i) % n;
    chkmax(ans, a[r] - a[l]);
  }

  // int mx = *max_element(a.begin(), a.end());
  // int mi = *min_element(a.begin(), a.end());
  
  int mi = 1E9, mx = -1E9;

  for (int i = 1; i < n; i ++ ) {
    chkmax(mx, a[i]);
  }
  for (int i = 0; i < n - 1; i ++ ) {
    chkmin(mi, a[i]);
  }

  chkmax(ans, mx - a[0]);
  chkmax(ans, a.back() - mi);

  cout << ans << "\n";


  // if (mx == a.back() && mi == a.front()) {
  //   cout << mx - mi << "\n";
  //   return ;
  // } else {

  // }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
