/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-23 17:25:03
**/

#include <bits/stdc++.h>
// using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  ll n, k, b, s;
  std::cin >> n >> k >> b >> s;
  int x1 = b / n, x2 = b % n;
  // x2 个 (x1 + 1) * k + [0, k-1]
  // n - x2 个 x1 * k + [0, k-1]
  // ll l = 0, r = 0;
  ll l = 1ll * (x1 + 1) * k * x2 + 1ll * x1 * k * (n - x2);
  ll r = 1ll * ((x1 + 1) * k + k - 1) * x2 + 1ll * (x1 * k + k - 1) * (n - x2);
  if (s < l || s > r) {
    std::cout << "-1\n";
    return;
  }
  std::vector<ll> a(n);
  for (int i = 0; i < x2; i ++ ) {
    a[i] = (x1 + 1) * k;
    s -= a[i];
  }
  for(int i = x2; i < n; i ++ ) {
    a[i] = x1 * k;
    s -= a[i];
  }

  for(int i = 0; i < n; i ++ ) if(s) {
    ll now = std::min(s, k - 1);
    a[i] += now;
    s -= now;
  }
  for(ll &x: a) std::cout << x << " ";
  std::cout << "\n";



}

int main() {
  std::cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; std::cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
