/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-27 22:35:22
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n, m, sx, sy, d;
  cin >> n >> m >> sx >> sy >> d;

  // if (!d) {
  //   cout << n + m - 2 << "\n";
  //   return ;
  // }
  // if (abs(sx - n) + abs(sy - m) <= d || (sx + d >= n && sx - d <= 1) || (sy + d >= m && sy - d <= 1)) {
  //   cout << "-1\n";
  //   return ;
  // }  
  if (abs(sx - n) + abs(sy - m) <= d || (sx + d >= n && sx - d <= 1) || (sy + d >= m && sy - d <= 1) || (abs(sx - n) <= d && abs(sy - m) <= d) || (abs(sx - 1) <= d && abs(sy - 1) <= d)) {
    cout << "-1\n";
    return ;
  }  

  cout << n + m - 2 << "\n";

  
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
