/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-23 20:05:03
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  string s; cin >> s; s = " " + s;  
  auto t = s;
  ll ans = 0;
  for (int i = 1; i <= n; i ++ ) {
    for (int j = i; j <= n; j += i) if (t[j] == '0') {
      if (s[j] == '0') {
        ans += i;
        s[j] = '1';
      }
      // cout << ans << " ";
    } else {
      break;
    }
  } 
  cout << ans << "\n";
  // vector<int> cnt(n + 1);
  // for (int i = n; i >= 1; i -- ) if (s[i] == '0') {
  //   cnt[i] = 0;
  // }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
