/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-29 22:35:13
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 110;
constexpr int P = 998244353;

ll fact[N + 1], infact[N + 1];

ll ksm(ll a, ll b, ll ret = 1) {
  while (b) {
    if (b & 1) ret = ret * a % P;
    b >>= 1;
    a = a * a % P;
  }
  return ret;
}

void init() {
  fact[0] = 1;
  for (int i = 1; i <= N; i ++ ) fact[i] = fact[i - 1] * i % P;
  infact[N] = ksm(fact[N], P - 2);
  for (int i = N - 1; i >= 0; i -- ) infact[i] = infact[i + 1] * (i + 1) % P;
}

ll C(int a, int b) {
  if (a < b) return 0;
  return fact[a] * infact[b] % P * infact[a - b] % P;
}

bool chk(int n) {
  if (n == 2) {
    cout << "1 0 1\n"; return true;
  } else if (n == 4) {
    cout << "3 2 1\n"; return true;
  } else if (n == 6) {
    cout << "12 7 1\n"; return true;
  } else if (n == 8) {
    cout << "42 27 1\n"; return true;
  }
  return false;
}

void solve() {
  int n; cin >> n;  
  if (chk(n)) return ;
  ll ans = 0;
  ll sum = C(n, n / 2);
  while (n) {
    if (n <= 2) break;
    ans += C(n - 2, n / 2 - 2); ans %= P;
    ans += C(n - 3, n / 2 - 2); ans %= P;
    n -= 4;
  }
  ll a = ans, b, c = 1;
  b = (sum - a - c) % P;
  b = (b + P) % P;
  cout << b << " " << a << " " << c << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  init();
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
