/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-08 22:35:01
 **/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define rep(i, a, b) for (int i = a; i <= b; i++)
#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T>
void chkmax(T &x, T y) {
  x = max(x, y);
}
template <typename T>
void chkmin(T &x, T y) {
  x = min(x, y);
}

constexpr int N = 3E5 + 10;

ll exgcd(ll a, ll b, ll &x, ll &y) {  //返回gcd(a,b) 并求出解(引用带回)
  if (b == 0) {
    x = 1, y = 0;
    return a;
  }
  ll x1, y1, gcd;
  gcd = exgcd(b, a % b, x1, y1);
  x = y1, y = x1 - a / b * y1;
  return gcd;
}

struct node {
  int a, b;
  bool operator<(const node &T) const { return T.a - T.b < a - b; }
} pepper[N];

int n, m;
ll pre[N], suf[N];

void solve() {
  cin >> n;
  for (int i = 1; i <= n; i++) {
    cin >> pepper[i].a >> pepper[i].b;
  }

  sort(pepper + 1, pepper + 1 + n);

  int mid = 0;  // search the middle
  for (int i = 1; i <= n; i++) {
    if (pepper[i].a - pepper[i].b >= 0) mid ++;
    pre[i] = pre[i - 1] + pepper[i].a;
  }
  for (int i = n; i >= 1; i--) {
    suf[i] = suf[i + 1] + pepper[i].b;
  }

  cin >> m;

  while (m--) {
    ll a, b;
    cin >> a >> b;
    ll x, y;
    exgcd(a, b, x, y);
    ll d = a * x + b * y, lcm = a * b / d;

    if (n % d) { cout << "-1\n"; continue; }
    //ax + by = n
    x *= n / d, y *= m / d; 
    ll t = b / d;
    // x 的最小非负整数解 
    x = (x % t + t) % t; y = (n - a * x) / b;
    if (y < 0) { cout << "-1\n"; continue; }

    ll res = 0;
    a = a * x, b = b * y;
    if (mid > a) {
      //
      ll k = (mid - a) / lcm;
      a += k * lcm, b -= k * lcm;
      chkmax(res, pre[a] + suf[n - b + 1]);
      if (b - lcm >= 0) chkmax(res, pre[a + lcm] + suf[n - b + lcm + 1]);
    } else {
      ll k = (a - mid) / lcm;
      a -= k * lcm, b += k * lcm;
      chkmax(res, pre[a] + suf[n - b + 1]);
      if (a - lcm >= 0) chkmax(res, pre[a - lcm] + suf[n - b - lcm + 1]);
    }

    cout << res << "\n";

  }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1;  // cin >> T;
  while (T--) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
