/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-30 22:50:51
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  switch (n % 4) {
  case 0:
    for (int i = 0; i < n; i ++ ) {
      cout << i << " \n"[i == n - 1];
    }
    break;
  case 1:
    cout << "0 ";
    for (int i = 0; i < n - 1; i ++ ) {
      cout << (1 << 30) + i << " \n"[i == n - 2];
    }
    break;
  case 2:
    for (int i = 0; i < n - 6; i ++ ) cout << i << " ";
    for (auto i : {4, 1, 2, 12, 3, 8}) {
      cout << (1 << 30) + i << " \n"[i == 8];
    }
    break;
  case 3:
    for (int i = 0; i < n - 3; i ++ ) cout << i << " ";
    cout << (1 << 29) << " ";
    cout << (1 << 30) << " ";
    cout << (1 << 29) + (1 << 30) << "\n";
    break;
  default:
    break;
  }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
