/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-30 22:50:51
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  vector<int> cnt(3);
  map<string, int> mp;
  vector<vector<string> > a(3, vector<string>(n));
  for (int i = 0; i < 3; i ++ ) {
    for (int j = 0; j < n; j ++ ) {
      cin >> a[i][j];
      mp[a[i][j]] ++;
    }
  }
  for (int i = 0; i < 3; i ++ ) {
    for (int j = 0; j < n; j ++ ) {
      if (mp[a[i][j]] == 1) {
        cnt[i] += 3;
      } else if(mp[a[i][j]] == 2) {
        cnt[i] ++;
      }
    }
  }
  for (int i = 0; i < 3; i ++ ) {
    cout << cnt[i] << " \n"[i == 2];
  }
  
}


int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
