/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-25 22:35:02
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }
constexpr int N = 1E5 + 10;
// int x[N], t[N];
pair<double, double> a[N];
void solve() {
  int n; cin >> n;
  for (int i = 1; i <= n; i ++ ) {
    cin >> a[i].first;
  }  
  for (int i = 1; i <= n; i ++ ) {
    cin >> a[i].second;
  }  
  sort(a + 1, a + 1 + n);
  double l = 0, r = 3E8;
  double ans = -1;
  for (int t = 0; t < 500; t ++ ) {
    double mid = (l + r) / 2;
    double left = 0, right = 3E8;
    bool flag = true;
    for (int i = 1; i <= n && flag; i ++ ) {
      if (mid < a[i].second) {
        flag = false;
      } else {
        auto last = mid - a[i].second;
        double L = a[i].first - last, R = a[i].first + last;
        // q求交
        //L, R left, right
        if (right < L || left > R) {
          flag = false;
        } else {
          chkmax(left, L);
          chkmin(right, R);
        }
      }
    }
    if (left > right) flag = false;
    
    if (flag) {
      r = mid;
      ans = left;
    } else {
      l = mid;
    }
  }

  cout << fixed << setprecision(10);
  cout << ans << "\n";

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
