/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-23 20:05:03
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  vector<ll> a(n);
  for (ll &x: a) cin >> x;
  sort(a.begin(), a.end());
  ll ans = INT_MAX;
  for (int i = 0; i < n; i ++ ) {
    for (int j = i + 1; j < n; j ++ ) {
      for (int k = j + 1; k < n; k ++ ) {
        chkmin(ans, abs(a[i] - a[j]) + abs(a[k] - a[j]));
        chkmin(ans, abs(a[i] - a[j]) + abs(a[k] - a[i]));
        chkmin(ans, abs(a[i] - a[k]) + abs(a[k] - a[j]));
      }
    }
  }
  cout << ans << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
