/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-10-15 22:35:05
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  vector<int> a(n + 1), s(n + 1);
  for (int i = 1; i <= n; i ++ ) {
    cin >> a[i];
    s[i] = s[i - 1] + a[i];
  }
  if (is_sorted(a.begin() + 1, a.end())) {
    return cout << "0\n", void();
  }
  int ans = INT_MAX;
  for (int i = 1; i <= n; i ++ ) {
    // [i, n] 全是 > 1
    int nowl = s[i - 1];
    int nowr = (n - i + 1) - (s[n] - s[i - 1]);
    int now = max(nowl, nowr);
    chkmin(ans, now);
  }
  cout << ans << "\n";
  
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
