/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-23 20:05:03
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 2E5 + 10;
ll a[N], b[N], suf[N];

void solve() {
  int n, k; cin >> n >> k;
  for (int i = 1; i <= n; i ++ ) cin >> a[i];
  int m = 0;
  for (int i = 1; i < k; i ++ ) {
    int j = i;
    ll sum = a[i];
    while (j + 1 < k && a[j + 1] * a[i] > 0) {
      ++ j;
      sum += a[j];
    }
    b[++ m ] = sum;
    i = j;
  }
  b[++ m ] = a[k];
  auto p = m;
  for (int i = k + 1; i <= n; i ++ ) {
    int j = i;
    ll sum = a[i];
    while (j + 1 <= n && a[j + 1] * a[i] > 0) {
      ++ j;
      sum += a[j];
    }
    b[++ m ] = sum;
    i = j;
  }
  // cout << m << "\n";
  // for (int i = 1; i <= m; i ++ ) {
  //   cout << b[i] << " \n"[i == m];
  // }
  k = p;

  queue<pair<ll, ll> > q1, q2;
  ll cost = 0, add = 0;
  for (int i = k + 1; i <= m; i ++ ) {
    add += b[i];
    chkmin(cost, add);
    if (add >= 0 || i == m) {
      q1.push({cost, add});
      // cout << cost << " " << add << "\n";
      cost = 0, add = 0;
    } 
  }
  // cout << "-----\n";
  cost = 0, add = 0;
  for (int i = k - 1; i >= 1; i -- ) {
    add += b[i];
    chkmin(cost, add);
    if (add >= 0 || i == 1) {
      q2.push({cost, add});
      // cout << cost << " " << add << "\n";
      cost = 0, add = 0;
    } 
  }
  // cout << "-----\n";
  ll now = b[k];
  // debug(now);
  while (true) {
    if (q1.empty() || q2.empty()) {
      if (now >= 0) {
        cout << "YES\n";
      } else {
        cout << "NO\n";
      }
      return ;
    } else {
      // auto t1 = q1.front();
      // auto t2 = q2.front();
      auto [cost1, add1] = q1.front();
      auto [cost2, add2] = q2.front();
      // cout << now + cost1 << " " << now + cost2 << "\n";
      // cout << "=-----=\n";
      if (cost1 > cost2) {
        if (now + cost1 >= 0) {
          now += add1;
          q1.pop();
        } else {
          cout << "NO\n";
          return ;
        }
      } else {
        if (now + cost2 >= 0) {
          now += add2;
          q2.pop();
        } else {
          cout << "NO\n";
          return ;
        }
      }
    }
  }
  
  

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
