/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-23 20:05:03
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }
constexpr int N = 1E3 + 10;
int a[N], b[N][N];

void solve() {
  int n; cin >> n;
  for (int i = 0; i < n; i ++ ) {
    cin >> a[i];
  }
  for (int i = 0, j; i < n; i ++ ) {
    b[i][i] = a[i];
    j = i; while (j + 1 < n) {
      ++ j;
      b[i][j] = b[i][j - 1] + i;
    }
    j = i; while (j - 1 >= 0) {
      -- j;
      b[i][j] = b[i][j + 1] - i;
    }
  }
  for (int i = 0; i < n; i ++ ) {
    for (int j = 0; j < n; j ++ ) {
      cout << ((b[i][j] % n) + n) % n << " \n"[j + 1 == n];
    }
  }
  // cout << __cplusplus << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; // cin >> T;
  while (T --) solve();
  // cout << "hello world" ;
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
