/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-30 22:50:51
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  string s; cin >> s;
  // for (int i = 0; )?

  long long now = 0;

  for (int i = 0; i < n; i ++ ) if (s[i] == 'L') {
    now += i;
  } else {
    now += n - i - 1;
  }

  vector<long long> ans(n, -1);
  for (int i = 0, l = 0, r = n - 1; i < n; ) {
    // int mx1 = max(l, n - l - 1),
    ll mi1 = min(l, n - l - 1), mx1 = max(l, n - l - 1);
    ll mi2 = min(r, n - r - 1), mx2 = max(r, n - r - 1);
    // auto [mi1, mx1] = minmax(l, n - l - 1);
    // auto [mi2, mx2] = minmax(r, n - r - 1);

    int s1, s2;
    if (s[l] == 'L') s1 = l;
    else s1 = n - l - 1;
    if (s[r] == 'L') s2 = r;
    else s2 = n - r - 1;
    // debug(l, r, mx1, mi1, mx2, mi2);
    // cout << "> " << mx1 - mi1 << " " << mx2 - mi2 << " " << s1 << " " << s2 << "\n";
    if (mx1 == s1 && mx2 == s2) {
      l ++, r --;
    }  else if (mx1 == s1) {
      now += mx2 - mi2;
      ans[i] = now;
      l ++;
      r --;
      ++ i;
    } else if (mx2 == s2) {
      now += mx1 - mi1;
      ans[i] = now;
      r --;
      l ++;
      ++ i; 
    } else {
      if (mx1 - mi1 >= mx2 - mi2) {
        now += mx1 - mi1;
        ans[i] = now;
        l ++;
      } else {
        now += mx2 - mi2;
        ans[i] = now;
        r --;
      }
      ++ i;
      
    }
    if (l > r) break;
  } 
  for (int i = 0; i < n; i ++ ) {
    if (ans[i] == -1ll) ans[i] = now;
    cout << ans[i] << " \n"[i == n - 1];
  }
  
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
