/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-25 22:35:02
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  string s; cin >> s;
  int n = s.size();
  //1 8 7 3 2 1 9
  string t;
  vector<int> idx(10, -1);
  for (int i = 0; i < (int)s.size(); i ++ ) {
    chkmax(idx[s[i] - '0'], i);
  }
  vector<int> cnt(10, 0);
  for (char c = '0'; c <= '9'; c ++ ) {
    for (int i = 0; i < n; i ++ ) if (s[i] == c) {
      bool flag = false;
      for (int j = 0; j < c - '0'; j ++ ) if (idx[j] > i) {
        flag = true;
      }
      if (flag) {
        cnt[min(9, c - '0' + 1)] ++;
      } else {
        cnt[c - '0'] ++;
      }
    }
  }
  for (int i = 0; i < 10; i ++ ) {
    t += string(cnt[i], (char)('0' + i));
  }
  // reverse(t.begin(), t.end());
  cout << t << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
