/* Generated by powerful Codeforces Tool
 * Author: 01shijian
 * Time: 2022-08-10 08:51:26
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int p = 998244353;

constexpr int N = 2E5 + 10;

ll f[N];
void add(ll &x, ll y) {
  x += y; x %= p;
}

// ll f[N];
//f[i] = f[i - 1] + f[i - 3] + f[i - 5] + ... + f[]

ll ksm(ll a, ll b, ll ret = 1) {
  while(b) {
    if(b & 1) ret = ret * a % p;
    b >>= 1;
    a = a * a % p;
  }
  return ret;
}

void solve1() {
  int n; cin >> n;
  f[1] = 1, f[2] = 1, f[3] = 2;
  for(int i = 4; i <= n; i ++ ) {
    ll now = f[i - 2];
    add(now, f[i - 1]);
    f[i] = now;
  }

  ll y = ksm(ksm(2, n), p - 2);

  cout << f[n] * y % p;

}

void solve2() {
  int n; cin >> n;
  f[0] = 1, f[1] = 1, f[2] = 1, f[3] = 2;
  ll sum1 = 3, sum2 = 2;
  for(int i = 4; i <= n; i ++ ) if(i & 1) {
    f[i] = sum2;
    add(sum1, f[i]);
  } else {
    f[i] = sum1; 
    add(sum2, f[i]);
  }
  ll y = ksm(ksm(2, n), p - 2);

  cout << f[n] * y % p;
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; //cin >> T;
  while (T --) solve2();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
