/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-11-04 22:35:11
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  vector<int> a(n);
  for (auto& x : a) cin >> x; //x = abs(x);
  ll sum1 = 0, sum2 = 0;
  bool f1 = false, f2 = false;
  for (int &x: a) if (x > 0) {
    sum1 += x;
    f1 = true;
  } else if (x < 0) {
    sum2 -= x;
    f2 = true;
  } else {
    f1 = f2 = true;
  }

  if (f1 && f2) {
    cout << max(sum1, sum2) - min(sum1, sum2) << "\n";
  } else if (f1) {
    cout << sum1 - 2 * (*min(a.begin(), a.end())) << "\n";
  } else {
    cout << sum2 + 2 * (*max(a.begin(), a.end())) << "\n";
  }

  
  
  


  
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
