/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-06 22:35:02
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n, m; cin >> n >> m;
  if (n == 1) {
    cout << "Yes\n";
    cout << m << "\n"; return ;
  } 
  if (m < n) {
    cout << "No\n";
    return ;
  }

  if (n == m) {
    cout << "Yes\n";
    for (int i = 1; i <= n; i ++ ) cout << 1 << " \n"[i == n];
    return; 
  } else {
    if (n & 1) {
      cout << "Yes\n";
      cout << m - n + 1 << " ";
      for (int i = 1; i < n; i ++ ) cout << "1 ";
      cout << "\n";
    } else {
      if (m & 1) {
        cout << "No\n";
      } else {
        cout << "Yes\n";
        for (int i = 1; i <= n - 2; i ++ ) {
          cout << "1 ";
        }
        m -= n - 2;
        cout << m / 2 << " " << m / 2 << "\n";
      }
    }
  }

  // cout << "Yes\n";
  // cout << m - n 
  
  //

  // 1 2 3

  vector<int> a(n);


  // sum{a_i} = m
  // a is interesting

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
