/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-30 13:47:50
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 5E5 + 10;

int cnt[2][N];

void solve() {
  int n, m; cin >> n >> m;
  for (int i = 0; i < m; i ++ ) {
    int x, y; cin >> x >> y;
    cnt[0][x] ++, cnt[1][y] ++;
  }
  int x = 0, y = 0;
  for (int i = 1; i <= n; i ++ ) {
    x += (cnt[0][i] == n);
  }
  for (int i = 1; i <= n; i ++ ) {
    y += (cnt[1][i] == n);
  }
  cout << n - max(x, y) << "\n";

}


int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; // cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
