/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-08-09 19:41:13
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

struct node {
  int l, r, id;
  bool operator < (const node &T) const {
    if(l != T.l) return l < T.l;
    return r > T.r;
  }
};

void solve() {
  string s; cin >> s;
  // vector<node> seg;
  int n; cin >> n;
  vector<array<int, 2> > a(s.size() + 10, {0, 0});
  for(int i = 0; i < n; i ++ ) {
    string t; cin >> t;
    for(int j = 0; j < s.size(); j ++ ) {
      if(s.substr(j, t.size()) == t) { //1 2 3
        if(a[j + 1][0] < j + (int)t.size()) {
          a[j + 1] = {j + (int)t.size(), i + 1};
        }
      }
    }
  }
  // cout << "-----\n";
  // cout << s << "\n";
  // for(int i = 1; i <= s.size(); i ++ ) {
  //   cout << i << " " << a[i][0] << "\n";
  // }
  // cout << "-----\n";

  if(a[1][0] == 0) {
    cout << "-1\n";
    return;
  }

  vector<array<int, 2> > ans;

  auto [r, id] = a[1];
  ans.push_back({a[1][1], 1});
  int mx = 1;
  for(int i = 2; i <= s.size(); i ++ ) {
    if(i > r + 1) {
      ans.push_back({id, mx});
      r = a[mx][0];
    }

    if(r == (int)s.size()) break;

    if(i <= r + 1) {
      if(a[i][0] > a[mx][0]) {
        mx = i;
        id = a[i][1];
      }
    }
  }

  if(a[mx][0] > r) {
    ans.push_back({id, mx});
    r = a[mx][0];
  }

  // cout << s << "\n";
  // cout << r << "\n";
  // // for(auto [u, v]: ans) {
  // //   cout << u << " " << v << "\n";
  // // }
  if(r == (int)s.size()) {
    cout << ans.size() << "\n";
    for(auto [u, v]: ans) {
      cout << u << " " << v << "\n";
    }
  } else {
    cout << "-1\n";
  }
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
