/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-29 22:35:13
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 4E5 + 10;

int q[N];

void solve() {
  int n, k; cin >> n >> k;
  vector<int> parent(n + 1), depth(n + 1, 0), cnt(n + 1); //, cntson(n + 1); 
  vector<vector<int> > son(n + 1);
  for (int i = 2; i <= n; i ++ ) {
    cin >> parent[i];
    son[parent[i]].emplace_back(i);
    // cntson[parent[i]] ++;
  }
  if (n == 1) return cout << "0\n", void();
  int l = 1, r = 0, mx = 0;
  function<void(int)> dfs = [&] (int u) {
    chkmax(r, depth[u]);
    cnt[depth[u]] ++;
    for(int v: son[u]) {
      depth[v] = depth[u] + 1;
      dfs(v);
    }
  };

  dfs(1);
  
  mx = r;

  auto check = [&] (int x) -> bool {
    // cnt 
    vector<int> dp(mx + 10);
    int hh = 0, tt = 0;
    q[0] = mx + 1;
    for (int i = mx; i >= 0; i -- ) {
      // dp[i] = min(dp[i + 1], dp[min(i + x, mx + 1)]) + cnt[i];
      if (hh <= tt && q[hh] - i > x) hh ++;
      dp[i] = dp[q[hh]] + cnt[i];
      // if (hh <= tt) dp[i] = dp[q[hh]] + cnt[i];
      // else dp[i] = cnt[i];
      while (hh <= tt && dp[q[tt]] >= dp[i]) -- tt;
      q[++ tt] = i; 
    }   
    // debug(x); debug(dp);
    for (int i = 0; i <= x + 1; i ++ ) if (dp[i] <= k) {
      return true;
    }
    return false;
  };
  
  while (l < r) {
    int mid = (l + r) / 2;
    if (check(mid)) r = mid;
    else l = mid + 1;
  }

  cout << l << "\n";

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}
/*
 *
 *　　┏┓　　　┏┓+ +

 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
