/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-08-27 22:35:22
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#define rep(i, a, b) for (int i(a); i <= b; ++ i)

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

constexpr int N = 1E5 + 10;

int a[N], b[N];

void solve() {
  int n; cin >> n;
  rep (i, 1, n) cin >> a[i];
  rep (i, 1, n) cin >> b[i];

  int now = 0;
  for (int j = 29; j >= 0; j -- ) {
    now |= 1 << j;
    map<int, int> mp1;
    for (int i = 1; i <= n; i ++ ) {
      mp1[a[i] & now] ++;
    }

    for (int i = 1; i <= n; i ++ ) {
      mp1[(b[i] & now) ^ now] --;
    }
    
    bool flag = true;
    for (auto &[k, v]: mp1) {
      if (v != 0) {
        flag = false;
      }
    }

    if (!flag) {
      now ^= 1 << j;
    }
    // for (auto [k, v]: mp1) {
    //   if()
    // }
  }
  cout << now << "\n";
  // c = a ^ b
  // c & 

}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
