/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-30 13:47:50
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }
using ull = unsigned long long;
using HH = pair<ull, ull>;


constexpr int N = 5E5 + 10;
constexpr HH mod = {1000000007, 1000000009};

mt19937 rnd(random_device{}());

HH base[N], a[N];

HH operator * (const HH& a, const HH& b) {
  return make_pair(a.first * b.first % mod.first, a.second * b.second % mod.second);
}

HH operator * (const HH& a, const ull& b) {
  return make_pair(a.first * b % mod.first, a.second * b % mod.second);
}

HH operator + (const HH& a, const HH& b) {
  return make_pair(a.first + b.first % mod.first, a.second + b.second % mod.second);
}

HH operator-(const HH &a, const HH &b) {
  return make_pair((a.first - b.first + mod.first) % mod.first, (a.second - b.second + mod.second) % mod.second);
}


void init() {
  base[0] = {1, 1};
  base[1] = {rnd() % mod.first, rnd() % mod.second};
  for (int i = 2; i < N; i ++ ) {
    base[i] = base[i - 1] * base[1];
  }
}

HH get(string &s) {
  a[0] = base[0];
  int n = s.size();
  for (int i = 1; i <= n; i ++ ) {
    a[i] = a[i - 1] * base[1] + base[0] * (s[i - 1] - 'a' + 10);
  }
  return a[n];
}

HH get(int l, int r) {
  return a[r] - (a[l - 1] * base[r - l + 1]);
}

map<HH, int> mp;

void gen(string &s) {
  
}

void solve() {
  int n; cin >> n;
  vector<string> a(n);
  for (auto &x: a) cin >> x;
  sort(a.begin(), a.end(), [&](string &x, string &y){
    auto lx = x.size(), ly = y.size();
    if (lx != ly) return lx < ly;
    return x < y;
  });
  for (int i = 0; i < n; i ++ ) {

  }

}


int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  init();
  int T = 1; // cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
