/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-08-09 19:41:13
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n, h, m; cin >> n >> h >> m;
  int ansh = -1, ansm = -1;
  for(int i = 0; i < n; i ++ ) {
    int H, M; cin >> H >> M;
    // if(H > h || (H == h && M >= m)) {
    if(H < h || (H == h && M < m)) {
      H += 24;
    }
    if(ansh == -1) {
      ansh = H - h, ansm = M - m;
      if(ansm < 0) ansm += 60, ansh --;
    } else {
      auto resh = H - h, resm = M - m;
      if(resm < 0) resm += 60, resh --;
      if(resh * 60 + resm < ansh * 60 + ansm) {
        ansh = resh, ansm = resm;
      }
    }
    // }
  }
  cout << ansh << " " << ansm << "\n";
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
