/* Generated by powerful Codeforces Tool
 * Author: SmartNanfeng
 * Time: 2022-09-06 22:35:02
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

void solve() {
  int n; cin >> n;
  string s; cin >> s;
  vector<int> a(n << 1);
  a[0] = 1;
  for (int i = 1; i < n * 2; i ++ ) {
    a[i] = a[i - 1] + (s[i] == '(' ? 1 : -1);
  }
  // int cnt = count(a.begin(), a.end(), 0);
  int cnt = 0;
  for (int i = 1; i < n * 2; i ++ ) {
    if (s[i] == '(' && s[i - 1] == ')') cnt ++;
  }
  cout << n - cnt << "\n";
  // if (cnt == 1) {
  //   cout << n << "\n";
  // } else {
  //   cout << n - cnt + 1 << "\n";
  // } 
}

int main() {
  cin.tie(nullptr)->sync_with_stdio(false);
  int T = 1; cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
