/* Generated by powerful Codeforces Tool
 * Author: nanfeng1997
 * Time: 2022-09-12 22:36:26
**/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

#ifdef LOCAL
#include <debugger>
#else
#define debug(...) 42
#endif

template <typename T> void chkmax(T &x, T y) { x = max(x, y); }
template <typename T> void chkmin(T &x, T y) { x = min(x, y); }

ll query(ll x, ll y) {
  cout << "? " << x << " " << y << endl;
  ll p; cin >> p;
  return p;
}

// void solve1() {
  
//   while (true) {
//     ll R = 1;
//     //假设我现在查到了 ans ，那么如果ans <= R - ans
//     //那么 n = R + t
//     // 即是 [1, R] 由 ans 和 R - ans + t 组成
//     // 反之如果 ans > R - ans
//     // 那么 可以查 R + ans
//     if (ans == -1) {
//       R /= 2;
//     } else {
//       ll inc = max(ans, R - ans);

//     }
//   }
// }

void solve() {
  map<long long, int> mp;
  for (int i = 1; i <= 25; i ++ ) {
    auto t1 = query(1, i + 1);
    auto t2 = query(i + 1, 1);
    if (t1 == -1 || t2 == -1) {
      cout << "! " << i << "\n";
      return ;
    }
    mp[t1 + t2] ++;
  }
  int va = 0;
  ll ans;
  for (auto [k, v]: mp) {
    if (v > va) {
      va = v;
      ans = k;
    }
  }
  cout << "! " << ans << "\n";
}

int main() {
  int T = 1; // cin >> T;
  while (T --) solve();
  return 0;
}

/*
 *
 *　　┏┓　　　┏┓+ +
 *　┏┛┻━━━┛┻┓ + +
 *　┃　　　　　　　┃
 *　┃　　　━　　　┃ ++ + + +
 *  ████━████+
 *  ◥██◤　◥██◤ +
 *　┃　　　┻　　　┃
 *　┃　　　　　　　┃ + +
 *　┗━┓　　　┏━┛
 *　　　┃　　　┃ + + + +Code is far away from 　
 *　　　┃　　　┃ + bug with the animal protecting
 *　　　┃　 　 ┗━━━┓ 神兽保佑,代码无bug　
 *　　　┃ 　　　　　　 ┣┓
 *　　  ┃ 　　　　　 　┏┛
 *　    ┗┓┓┏━┳┓┏┛ + + + +
 *　　　　┃┫┫　┃┫┫
 *　　　　┗┻┛　┗┻┛+ + + +
 */
